server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gzwrrr/SpringCloudConfig.git
          search-paths:
            - SpringCloudConfig
      label: master
  rabbitmq:
    host: 124.222.14.57
    port: 5672
    username: gzwrrr
    password: 963gzw@wl.


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7011/eureka

# rabbitmq 相关的配置，暴露 bus 刷新配置的断点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
