server:
  port: 8008

spring:
  application:
    name: cloud-stream-provider
  # 设置 rabbitmq 的相关的环境配置
  rabbitmq:
    host: 124.222.14.57
    port: 5672
    username: gzwrrr
    password: 963gzw@wl.
  cloud:
    stream:
      # 配置要绑定的 rabbitmq 的服务信息
      binders:
        # 表示定义的名称，用于 binding 整合
        defaultRabbit:
          # 消息组件类型
          type: rabbit
      # 服务整合处理
      bindings:
        # 这是一个通道的名称
        input:
          # 表示要使用的 Exchange 的名称
          destination: studyExchange
          # 设置消息类型
          content-type: application/json
          # 设置要绑定的消息服务的具体设置
          binder: defaultRabbit
          # 设置分组，如果不是同一个组会出现重复消费的问题，还可以起到持久化的作用，故障停机再重启还是能消费之前未消费的信息，所以一定要配置分组
          group: gontoyA

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7011/eureka
#  instance:
#    # 设置心跳的时间间隔（默认是30秒）
#    lease-renewal-interval-in-seconds: 2
#    # 如果现在超过了5秒的间隔（默认是90秒）
#    lease-expiration-duration-in-seconds: 5
#    # 在信息列表时显示主机名称
#    instance-id: send-8801.com
#    # 访问的路径变为IP地址
#    prefer-ip-address: true