server:
  port: 3355

spring:
  application:
    name: cloud-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        # 说明 3355 会被 8080 的 sentinel 监控
        dashboard: localhost:8080
        # 默认 8719 端口，如果没有找到就一直 +1 直到找到未占用的端口
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: "*"